name: Update README Progress

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate Progress
        run: |
          PROGRESS=$(sh your_script.sh)  # Replace with actual script
          sed -i "s|![Progress](https://progress-bar.dev/[0-9]*)|![Progress](https://progress-bar.dev/$PROGRESS/)|g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated progress bar"
          git push
